### ISSUE TITLE
CJK Character support

### ISSUE THREAD

**Issue by Robpol86** [Robpol86/colorclass#14]
```
tests/test_width_and_alignment.py:16: in <module>
    (Color('{autoblue}世界你好{/autoblue}'), 8),
.tox/py26/lib/python2.6/site-packages/colorclass.py:391: in __new__
    obj = parent_class.__new__(cls, *args, **kwargs)
E   UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 5: ordinal not in range(128)
```

**Comment by Robpol86** [comment]
Was user error. Had to declare the string as unicode in python 2.6 (e.g. u'string').

```
(env)[Bosco colorclass (cjk)]$ python
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from colorclass import Color
>>> Color('{autoblue}世界你好{/autoblue}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "colorclass/core.py", line 65, in __new__
    instance = PARENT_CLASS.__new__(*color_args, **kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 5: ordinal not in range(128)
>>> Color(u'{autoblue}世界你好{/autoblue}')
Color(u'\x1b[94m\u4e16\u754c\u4f60\u597d\x1b[39m')
>>> ^D
(env)[Bosco colorclass (cjk)]$ python3
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 23 2015, 02:52:03) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from colorclass import Color
>>> Color(u'{autoblue}世界你好{/autoblue}')
Color('\x1b[94m世界你好\x1b[39m')
>>> ^D
(env)[Bosco colorclass (cjk)]$ python2.6
Python 2.6.9 (unknown, Oct 23 2015, 19:19:20) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from colorclass import Color
>>> Color(u'{autoblue}世界你好{/autoblue}')
Color(u'\x1b[94m\u4e16\u754c\u4f60\u597d\x1b[39m')
>>> 
```
